### ISSUE TITLE
API Climatempo

### ISSUE THREAD

**Issue by oliverthies** [adinan-cenci/climatempo-api#1]
Seria legal utilizarem a API oficial da Climatempo
https://advisor.climatempo.com.br

**Comment by oliverthies** [comment]
Essa url que vocês estão utilizando para baixar dados em breve vai deixar de funcionar!

**Comment by adinan-cenci** [comment]
Obrigado por informar.

**Comment by adinan-cenci** [comment]
Gostaria de agradecer @oliverthies por ter me chamado a atenção sobre isso.
Estamos trabalhando na versão 3 que irá usar da nova advisor api do climatempo.

**Comment by adinan-cenci** [comment]
Então, a nova versão 3.0.0 já usa a nova API do climatempo.
Obrigado novamente a @oliverthies

**Comment by oliverthies** [comment]
Valeu!!!!
Abs

Em 9 de dez de 2017 09:18, "Adinan Cenci" <notifications@github.com>
escreveu:
