### ISSUE TITLE
Falha ao acessar API

### ISSUE THREAD

**Issue by assuncaojr** [adinan-cenci/climatempo-api#2]
Não é bem uma Issue, mas... Ao tentar acessar a API, tenho recebido a mensagem de erro "Sorry, it was not possible to handle your request, if this problem persists, please contact us.", mesmo não atingido a cota diária de requisições.

Sabem o que poderia ser?

**Comment by adinan-cenci** [comment]
Você está correto amigo. Eu estou sofrendo o mesmo problema.
Mas isso no entanto parece ser um problema com o servidor do clima tempo.

Tente acessar no seu navegador e você vai ver a mesma mensagem de erro:
http://apiadvisor.climatempo.com.br/api/v1/forecast/locale/3477/days/15?token=SEU-TOKEN-AQUI

Parece que isso está acontecendo apenas com a previsão para os próximos 15 dias, a previsão para 73 horas e atual parecem estar funcionando normalmente.

Talvez eles estejam sofrendo com algum problema técnico.
Eu vou entrar em contato com eles. Obrigado por me informar.

**Comment by assuncaojr** [comment]
Parece ser um problema técnico deles, testei várias vezes hoje o acesso direto ao recurso e não tive sucesso. 

Eu que agradeço.

**Comment by adinan-cenci** [comment]
@assuncaojr Oi. O suporte do clima tempo me respondeu e confirmaram que foi um problema com os servidores deles mas já está funcionando novamente.

Obrigado e tudo de bom.
